json.id game.id
json.manufacturer game.manufacturer
json.console game.console
json.price game.price
json.storage game.storage
json.description game.description
json.image_url game.image_url
json.created_at game.created_at
json.updated_at game.updated_at
